const restaurantsModel = {
    name: "restaurants",
    state: [
        {
            id: 1,
            name: {
                ar: "كنتاكي",
                en: "KFC",
            },
            branch: {
                ar: "شارع المشتل",
                en: "ALmashtal St",
            },
            location: "الخرطوم, شارع المشتل",
            estTime: [25, 45],
            categories: [1, 2, 3],
            rate: 4.5,
            logo: require("../assets/kfc.png"),
            recommended: true,
            open: true,
        },
        {
            id: 2,
            name: {
                ar: "بيتزا هـت",
                en: "PizzaHut",
            },
            branch: {
                ar: "شارع المشتل",
                en: "ALmashtal St",
            },
            location: "الخرطوم, شارع المشتل",
            estTime: [15, 35],
            categories: [1, 2, 3],
            rate: 4,
            logo: require("../assets/pizzahut.png"),
            recommended: true,
            open: true,
        },
        {
            id: 3,
            name: {
                ar: "فودبوينت",
                en: "FoodPoint",
            },
            branch: {
                ar: "بحري",
                en: "Bhari",
            },
            location: "بحري, شارع الازهري",
            estTime: [20, 40],
            categories: [2, 3, 4, 9],
            rate: 4.5,
            logo: require("../assets/foodpoint.png"),
            recommended: true,
            open: true,
        },
        {
            id: 4,
            name: { ar: "فرايزو", en: "Friso" },
            branch: {
                ar: "بحري",
                en: "Bhari",
            },
            location: "بحري, شارع الازهري",
            estTime: [20, 40],
            categories: [10],
            rate: 4,
            logo: require("../assets/friso.jpg"),
            recommended: true,
            open: false,
        },
        {
            id: 5,
            name: { ar: "ديبونيرز", en: "Debonairs" },
            branch: {
                ar: "شارع المطار",
                en: "Airport St",
            },
            location: "الخرطوم, شارع المطار",
            estTime: [20, 40],
            categories: [1, 3, 9],
            rate: 4,
            logo: require("../assets/debonairs.png"),
            recommended: true,
            open: true,
        },
        {
            id: 6,
            name: { ar: "شيكانو", en: "Chicano" },
            branch: {
                ar: "شارع الوادي",
                en: "Alwadi St",
            },
            location: "امدرمان, شارع وادي",
            estTime: [20, 40],
            categories: [1, 3, 4],
            rate: 3.5,
            logo: require("../assets/chicano.png"),
            recommended: true,
            open: true,
        },
    ],
    reducers: {},
    effects: {},
};

export default restaurantsModel;
